---

- name: Update askismet
  subversion: repo=https://plugins.svn.wordpress.org/akismet/tags/{{ wordpress_akismet_version }} dest={{ wordpress_dir }}/wp-content/plugins/akismet
  become_user: '{{ wordpress_user }}'

- name: Install wordpress plugins
  subversion: repo=https://plugins.svn.wordpress.org/{{ item.name }}/{{ item.version }}/ dest={{ wordpress_dir }}/wp-content/plugins/{{ item.name }} force=yes
  become_user: '{{ wordpress_user }}'
  with_items: '{{ wordpress_plugins }}'
