---

- name: Install the vhost redirect(s) for {{ wordpress_site }}
  template: src=vhost_redirect.j2
            dest=/etc/nginx/sites-available/{{ wordpress_site }}_redirect
            mode=0644
  notify:
    - restart nginx

- name: Enable the {{ wordpress_shortname }} virtual host redirects
  file: path=/etc/nginx/sites-enabled/{{ wordpress_site }}_redirect
        src=/etc/nginx/sites-available/{{ wordpress_site }}_redirect
        state=link
  notify:
    - restart nginx

